### ISSUE TITLE
macos下Safari浏览器无法复制代码段

### ISSUE THREAD

**Issue by yejr** [zkqiang/wechat-mdeditor#1]
详情请见 [截图](http://imysql.com/wp-content/uploads/2019/09/QQ20190915-100646.png)

**Comment by zkqiang** [comment]
您好，经测试我这里可以，麻烦提供了具体复现的流程，和您的环境版本？

![image](https://user-images.githubusercontent.com/32983588/64931353-bcf7cc00-d86a-11e9-86f2-3cf048609b7f.png)
